// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clfnehuavfsufrmoefwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZm5laHVhdmZzdWZybW9lZndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTMyMzksImV4cCI6MjA3MTI4OTIzOX0.wEToB5RHgKfP-wAKWhGZW5bMiZfmAlZ6DvLDSENVhvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});