// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvdfrpmzexovxbjqtqtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZGZycG16ZXhvdnhianF0cXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTkxNDQsImV4cCI6MjA3MTM3NTE0NH0.HLQr7LhMPQpKfOPvkxokCkF6mIjsZcpXQlU8FJbwozo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});